name: oneapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+11

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_markdown: ^0.6.14
  http: ^0.13.5
  intl: ^0.18.0
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# flutter pub run flutter_launcher_icons -f pubspec.yaml
flutter_icons:
  image_path_android: 'assets/images/icon-710x710-android.png'
  image_path_ios: 'assets/images/icon-1024x1024.png'
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: 'assets/images/icon-1024x1024.png'
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: 'assets/images/icon-1024x1024.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/images/icon-1024x1024.png'

flutter:
  uses-material-design: true
